### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by badga** [badga/Collaborative-exams#1]
Finir la question @badga

**Comment by badga** [comment]
**# QuestionText.** 
@SidAhmedImloul  
@laminetamendjari

**Comment by SidAhmedImloul** [comment]
Ajouter @Omar à l'issue (même problème que @Sofiath).

**Comment by Omar90sh** [comment]
..

**Comment by Omar90sh** [comment]
Hii !!

**Comment by laminetamendjari** [comment]
Pour info : cette issue est assinée à YOUS MADJID et OMAR SHAGHAF YAGHI (Omar90sh)

**Comment by oliviercailloux** [comment]
Veuillez indiquer les assignees.

**Comment by oliviercailloux** [comment]
Les assignees doivent être indiqués via le système de GitHub, sinon mon suivi automatique ne fonctionne pas.

**Comment by oliviercailloux** [comment]
Protection contre nulls inexistante (commentaire déjà détaillé par ailleurs)
Contrat inexistant, pas de Javadoc. 
L’objet question est demandé immuable. Il faut donc un autre objet pour construire une question.
Absence d’interface MultipleChoiceQuestion.
Redundant specification of type arguments <Questions> (et autres similaires)
People devrait s’appeler Person, c’est ce qu’une instance représente.
Manque de clarté, en général, par exemple difficile de deviner que "questions" dans People représente les questions dont une personne est l’auteur (contrairement par exemple aux questions auxquelles elle aurait répondu).
Le code semble encore à l’état de brouillon, par exemple dans un des constructeurs des informations statiques sont ajoutées (sans-doute pour debug).
Tout semble dupliqué : Question et Questions, etc.
