### ISSUE TITLE
Servlets

### ISSUE THREAD

**Issue by SidAhmedImloul** [badga/Collaborative-exams#3]
Servlet NewQuestion(question): id, qui reçoit une question en format JSON ; servlet GetQuestion(id): question, qui envoie une question à partir de son id
La solution proposée se trouve dans le dossier **"Controller"**

**Comment by SidAhmedImloul** [comment]
Problème avec le compte de @Sofiath, quelqu'un peut l'ajouter en "Assignees" ?

**Comment by laminetamendjari** [comment]
Je ne trouve pas le compte de Sofiath

**Comment by laminetamendjari** [comment]
Peut etre ça va marcher si je commente :-)

**Comment by laminetamendjari** [comment]
C'est fait pour Sofiath Lanignan

**Comment by SidAhmedImloul** [comment]
Merci @laminetamendjari ;)

**Comment by oliviercailloux** [comment]
J’ai déjà attribué une note pour la fonctionnalité "Servlets", à jeffazzam et à laminetamendjari. Ce sont les deux assignees qui étaient sur cette fonctionnalité au moment de sa première fermeture. Je ne prends pas en compte les changements d’assignees ultérieurs.
Nous pouvons en discuter lors de la prochaine séance si vous avez des questions à ce sujet.
