### ISSUE TITLE
ServletsModify

### ISSUE THREAD

**Issue by SidAhmedImloul** [badga/Collaborative-exams#8]
Http ok. 
Il faut voir avec le prof si c'est ce qui est attendu + transformer en Jax-RS

**Comment by oliviercailloux** [comment]
Noté 8 janvier. Get ou Post, il faut choisir. Pas de commentaires auto-générés. Code fragile : conversion en ArrayList pourrait échouer (et est inutile) ; code difficile à lire (entre autres, non formatté), etc. (voir erreurs données par Eclipse et best practices, à discuter en séance). (Une question devrait être immuable.) Le servlet doit renvoyer le nouvel id.
